// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyzYBedHwpb5EJ9a7DwYEpy06ugPzDAU',
    appId: '1:785008047193:web:5011c0583d0a76572aed48',
    messagingSenderId: '785008047193',
    projectId: 'fawry-3608c',
    authDomain: 'fawry-3608c.firebaseapp.com',
    storageBucket: 'fawry-3608c.appspot.com',
    measurementId: 'G-1Y80NYKN5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqM5SH_PpLcuIujVl-0_vTgYAyVxHrrHM',
    appId: '1:785008047193:android:97fe3169c829469f2aed48',
    messagingSenderId: '785008047193',
    projectId: 'fawry-3608c',
    storageBucket: 'fawry-3608c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1wYpug5SZwmBD3LP8DrtXagUn2LE4Hc',
    appId: '1:785008047193:ios:3bf88918b1fa059c2aed48',
    messagingSenderId: '785008047193',
    projectId: 'fawry-3608c',
    storageBucket: 'fawry-3608c.appspot.com',
    iosClientId: '785008047193-ikl10tnsf39k2oac5vsvjn4ivburmo6t.apps.googleusercontent.com',
    iosBundleId: 'com.hyper.fawry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1wYpug5SZwmBD3LP8DrtXagUn2LE4Hc',
    appId: '1:785008047193:ios:11aeaaec1f7f624b2aed48',
    messagingSenderId: '785008047193',
    projectId: 'fawry-3608c',
    storageBucket: 'fawry-3608c.appspot.com',
    iosClientId: '785008047193-957i3nktrea6qhrro1r2n8fo4qgg67kn.apps.googleusercontent.com',
    iosBundleId: 'com.hyper.fawryApp',
  );
}
