part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const BOARDING = _Paths.BOARDING;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const ACTIVITYS = _Paths.ACTIVITYS;
  static const ADD_ACTIVITY = _Paths.ADD_ACTIVITY;
  static const VERIFY_REST_PASSWORD = _Paths.VERIFY_REST_PASSWORD;
  static const REST_PASSWORD = _Paths.REST_PASSWORD;
  static const PROFILE = _Paths.PROFILE;
  static const HISTORY = _Paths.HISTORY;
  static const SERVICES = _Paths.SERVICES;
  static const ADD_SERVICES = _Paths.ADD_SERVICES;
  static const PRINT = _Paths.PRINT;
  static const INVOICE = _Paths.INVOICE;
  static const START_NOW = _Paths.START_NOW;
  static const ENTER_REST_PASSWORD = _Paths.ENTER_REST_PASSWORD;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const BASIC = _Paths.BASIC;
  static const EDIT_SERVICES = _Paths.EDIT_SERVICES;
  static const PHONE = _Paths.PHONE;
  static const SHOW_INVOICES = _Paths.SHOW_INVOICES;
  static const SHOW_DEVICES = _Paths.SHOW_DEVICES;
  static const CHAT = _Paths.CHAT;
  static const REPORT = _Paths.REPORT;
  static const DETIALS_REPORT = _Paths.DETIALS_REPORT;
  static const MULTI_HISTORY = _Paths.MULTI_HISTORY;
  static const HISTORY2 = _Paths.HISTORY2;
  static const SELECT_LANG = _Paths.SELECT_LANG;
  static const ADS = _Paths.ADS;
  static const DETIALS_STOCK = _Paths.DETIALS_STOCK;
  static const FAVORITE = _Paths.FAVORITE;
  static const PURCHASE_INVOICE = _Paths.PURCHASE_INVOICE;
  static const PURCHASE_INVOICE_HISTORY = _Paths.PURCHASE_INVOICE_HISTORY;
  static const SALES_INVOICES = _Paths.SALES_INVOICES;
  static const DETIALS_STOCK_PRODUCT = _Paths.DETIALS_STOCK_PRODUCT;
  static const DETIALS_STOCK_COMPREHENSIVE = _Paths.DETIALS_STOCK_COMPREHENSIVE;
  static const ADD_ITEM = _Paths.ADD_ITEM;
  static const ITEMS = _Paths.ITEMS;
  static const ARCHIVES = _Paths.ARCHIVES;
  static const SALES_INVOICE_HISTORY = _Paths.SALES_INVOICE_HISTORY;
  static const COUPON = _Paths.COUPON;
  static const DELETE_COMPANY = _Paths.DELETE_COMPANY;
  static const SELECT_COMPANY_PURCHASE = _Paths.SELECT_COMPANY_PURCHASE;
  static const SELECT_COMPANY_SALES = _Paths.SELECT_COMPANY_SALES;
  static const ADS_APP = _Paths.ADS_APP;
  static const EDIT_ACTIVITY = _Paths.EDIT_ACTIVITY;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const BOARDING = '/boarding';
  static const LOGIN = '/login';
  static const SIGNUP = '/signup';
  static const ACTIVITYS = '/activitys';
  static const ADD_ACTIVITY = '/add-activity';
  static const VERIFY_REST_PASSWORD = '/verify-rest-password';
  static const REST_PASSWORD = '/rest-password';
  static const PROFILE = '/profile';
  static const HISTORY = '/history';
  static const SERVICES = '/services';
  static const ADD_SERVICES = '/add-services';
  static const PRINT = '/print';
  static const INVOICE = '/invoice';
  static const START_NOW = '/start-now';
  static const ENTER_REST_PASSWORD = '/enter-rest-password';
  static const CHANGE_PASSWORD = '/change-password';
  static const BASIC = '/basic';
  static const EDIT_SERVICES = '/edit-services';
  static const PHONE = '/phone';
  static const SHOW_INVOICES = '/show-invoices';
  static const SHOW_DEVICES = '/show-devices';
  static const CHAT = '/chat';
  static const REPORT = '/report';
  static const DETIALS_REPORT = '/detials-report';
  static const MULTI_HISTORY = '/multi-history';
  static const HISTORY2 = '/history2';
  static const SELECT_LANG = '/select-lang';
  static const ADS = '/ads';
  static const DETIALS_STOCK = '/detials-stock';
  static const FAVORITE = '/favorite';
  static const PURCHASE_INVOICE = '/purchase-invoice';
  static const PURCHASE_INVOICE_HISTORY = '/purchase-invoice-history';
  static const SALES_INVOICES = '/sales-invoices';
  static const DETIALS_STOCK_PRODUCT = '/detials-stock-product';
  static const DETIALS_STOCK_COMPREHENSIVE = '/detials-stock-comprehensive';
  static const ADD_ITEM = '/add-item';
  static const ITEMS = '/items';
  static const ARCHIVES = '/archives';
  static const SALES_INVOICE_HISTORY = '/sales-invoice-history';
  static const COUPON = '/coupon';
  static const DELETE_COMPANY = '/delete-company';
  static const SELECT_COMPANY_PURCHASE = '/select-company-purchase';
  static const SELECT_COMPANY_SALES = '/select-company-sales';
  static const ADS_APP = '/ads-app';
  static const EDIT_ACTIVITY = '/edit-activity';
}
